import type { Metadata } from "next"
import "../../shared/style/globals.css"
import "../../shared/style/reset.css"
import "../../shared/style/variables.css"
import { TChildren } from "@/shared/types/Children"
import { CombineProvider } from "@/shared/providers/CombineProvider"
import "@fontsource/roboto/300.css"
import "@fontsource/roboto/400.css"
import "@fontsource/roboto/500.css"
import "@fontsource/roboto/700.css"

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

const RootLayout = ({ children }: TChildren) => {
    return (
        <html lang='ru'>
            <body>
                <CombineProvider>{children}</CombineProvider>
            </body>
        </html>
    )
}

export default RootLayout
